"""Add description column to agents

Revision ID: b02025a14cd4
Revises: 117ab365bb6f
Create Date: 2025-02-09 05:38:28.478507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b02025a14cd4'
down_revision: Union[str, None] = '117ab365bb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('docs', sa.JSON(), nullable=True))
    op.drop_column('agents', 'ocs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('ocs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('agents', 'docs')
    # ### end Alembic commands ###
