"""Add description column to agents

Revision ID: ca6728f4b91c
Revises: 097ed04bd07e
Create Date: 2025-02-09 05:12:00.583957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6728f4b91c'
down_revision: Union[str, None] = '097ed04bd07e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agents_id', table_name='agents')
    op.drop_index('ix_agents_index_name', table_name='agents')
    op.drop_index('ix_agents_name', table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='agents_pkey')
    )
    op.create_index('ix_agents_name', 'agents', ['name'], unique=False)
    op.create_index('ix_agents_index_name', 'agents', ['index_name'], unique=False)
    op.create_index('ix_agents_id', 'agents', ['id'], unique=False)
    # ### end Alembic commands ###
