

class DocumentationScraper:
    def __init__(self, base_url, urls):
        self.urls = urls
        self.base_url = base_url
        self.visited = set()
        self.to_visit = []

    def _get_urls(self):
        return self.urls


urls = ["https://docs.arbitrum.io/welcome/arbitrum-gentle-introduction",
        "https://docs.arbitrum.io/welcome/get-started",
        "https://docs.arbitrum.io/for-devs/dev-tools-and-resources/chain-info",
        "https://docs.arbitrum.io/build-decentralized-apps/quickstart-solidity-remix",
        "https://docs.arbitrum.io/build-decentralized-apps/how-to-estimate-gas",
        "https://docs.arbitrum.io/build-decentralized-apps/public-chains",
        "https://docs.arbitrum.io/build-decentralized-apps/cross-chain-messaging",
        "https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/comparison-overview",
        "https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/block-numbers-and-time",
        "https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/rpc-methods",
        "https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/solidity-support",
        "https://docs.arbitrum.io/build-decentralized-apps/oracles/overview-oracles",
        "https://docs.arbitrum.io/build-decentralized-apps/precompiles/overview",
        "https://docs.arbitrum.io/build-decentralized-apps/precompiles/reference",
        "https://docs.arbitrum.io/build-decentralized-apps/nodeinterface/overview",
        "https://docs.arbitrum.io/build-decentralized-apps/nodeinterface/reference",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/overview",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/token-bridge-ether",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/token-bridge-erc20",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/bridge-tokens-programmatically/get-started",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/bridge-tokens-programmatically/how-to-bridge-tokens-standard",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/bridge-tokens-programmatically/how-to-bridge-tokens-generic-custom",
        "https://docs.arbitrum.io/build-decentralized-apps/token-bridging/bridge-tokens-programmatically/how-to-bridge-tokens-custom-gateway",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/node-providers",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/contract-addresses",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/chain-params",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/development-frameworks",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/web3-libraries-tools",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/monitoring-tools-block-explorers",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/debugging-tools",
        "https://docs.arbitrum.io/build-decentralized-apps/reference/mainnet-risks",
        "https://docs.arbitrum.io/for-devs/troubleshooting-building",
        "https://docs.arbitrum.io/sdk/introduction",
        "https://docs.arbitrum.io/sdk/migrate",
        "https://docs.arbitrum.io/sdk/reference/assetBridger/",
        "https://docs.arbitrum.io/sdk/reference/assetBridger/erc20Bridger",
        "https://docs.arbitrum.io/sdk/reference/assetBridger/ethBridger",
        "https://docs.arbitrum.io/sdk/reference/assetBridger/l1l3Bridger",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/address",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/constants",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/errors",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/event",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/message",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/networks",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/retryableData",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/rpc",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/signerOrProvider",
        "https://docs.arbitrum.io/sdk/reference/dataEntities/transactionRequest",
        "https://docs.arbitrum.io/sdk/reference/inbox/",
        "https://docs.arbitrum.io/sdk/reference/message/ChildToParentMessage",
        "https://docs.arbitrum.io/sdk/reference/message/ChildToParentMessageClassic",
        "https://docs.arbitrum.io/sdk/reference/message/ChildToParentMessageNitro",
        "https://docs.arbitrum.io/sdk/reference/message/ChildTransaction",
        "https://docs.arbitrum.io/sdk/reference/message/ParentToChildMessage",
        "https://docs.arbitrum.io/sdk/reference/message/ParentToChildMessageCreator",
        "https://docs.arbitrum.io/sdk/reference/message/ParentToChildMessageGasEstimator",
        "https://docs.arbitrum.io/sdk/reference/message/ParentTransaction",
        "https://docs.arbitrum.io/sdk/reference/utils/arbProvider",
        "https://docs.arbitrum.io/sdk/reference/utils/byte_serialize_params",
        "https://docs.arbitrum.io/sdk/reference/utils/eventFetcher",
        "https://docs.arbitrum.io/sdk/reference/utils/lib",
        "https://docs.arbitrum.io/sdk/reference/utils/multicall",
        "https://docs.arbitrum.io/sdk/reference/utils/types",
        "https://docs.arbitrum.io/launch-orbit-chain/a-gentle-introduction",
        "https://docs.arbitrum.io/launch-orbit-chain/orbit-quickstart",
        "https://docs.arbitrum.io/launch-orbit-chain/aep-license",
        "https://docs.arbitrum.io/launch-orbit-chain/configure-your-chain/common-configurations/customizable-challenge-period",
        "https://docs.arbitrum.io/launch-orbit-chain/maintain-your-chain/guidance/state-growth",
        ]
